Repository Atharr/Desafio_Spring, pull requests merged in 2022-10, with the labels that each got.

#1 Implementação dos requisitos 1, 2 e 3
  src/main/java/br/com/dh/Desafio_Spring/controller/ProductController.java
  src/main/java/br/com/dh/Desafio_Spring/dto/ProductDTO.java
  src/main/java/br/com/dh/Desafio_Spring/exception/ExceptionDetails.java
  src/main/java/br/com/dh/Desafio_Spring/exception/HandlerExceptions.java
  src/main/java/br/com/dh/Desafio_Spring/exception/NotFoundException.java
  src/main/java/br/com/dh/Desafio_Spring/model/Product.java
  src/main/java/br/com/dh/Desafio_Spring/repository/ProductRepo.java
  src/main/java/br/com/dh/Desafio_Spring/service/IProduct.java
  src/main/java/br/com/dh/Desafio_Spring/service/ProductService.java
Labels: enhancement

#2 Product filters
  src/main/java/br/com/dh/Desafio_Spring/controller/ProductController.java
  src/main/java/br/com/dh/Desafio_Spring/repository/ProductRepo.java
  src/main/java/br/com/dh/Desafio_Spring/service/IProduct.java
  src/main/java/br/com/dh/Desafio_Spring/service/ProductService.java
Labels: enhancement

#5 Customers validation
  pom.xml
  src/main/java/br/com/dh/Desafio_Spring/controller/CustomerController.java
  src/main/java/br/com/dh/Desafio_Spring/dto/CustomerDTO.java
  src/main/java/br/com/dh/Desafio_Spring/model/Customer.java
  src/main/java/br/com/dh/Desafio_Spring/repository/CustomerRepo.java
  src/main/java/br/com/dh/Desafio_Spring/service/CustomerService.java
  src/main/java/br/com/dh/Desafio_Spring/service/ICustomer.java
  src/main/resources/customers.json
Labels: bug, enhancement

#6 Customers (with filtering and sorting)
  pom.xml
  src/main/java/br/com/dh/Desafio_Spring/controller/CustomerController.java
  src/main/java/br/com/dh/Desafio_Spring/dto/CustomerDTO.java
  src/main/java/br/com/dh/Desafio_Spring/model/Customer.java
  src/main/java/br/com/dh/Desafio_Spring/repository/CustomerRepo.java
  src/main/java/br/com/dh/Desafio_Spring/service/CustomerService.java
  src/main/java/br/com/dh/Desafio_Spring/service/ICustomer.java
  src/main/resources/customers.json
Labels: enhancement

#7 feat: decrease product and update method
  src/main/java/br/com/dh/Desafio_Spring/repository/ProductRepo.java
  src/main/resources/products.json
  src/main/resources/purchase-result.json
Labels: feature
